# Data configuration
data:
    image_size: 512
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]

# Paths for images
paths:
    content_image: "assets/content.jpg"
    style_image: "assets/style.jpg"
    output_image: "output/generated.jpg"

# Model configuration
model:
    content_layers: ["conv4_2", "conv5_2"]
    style_layers: ["conv1_1", "conv2_1", "conv3_1", "conv4_1"]

# Style transfer configuration
style_transfer:
    alpha: 1.0
    beta: 1000.0
    epochs: 1000
    learning_rate: 0.01
    print_interval: 100
